#! /bin/bash

dnf --enablerepo=powertools install xz-lzma-compat -y
yum -y install perl-Archive-Extract-lzma-unlzma
yum -y install perl-Archive-Extract 
yum -y install frr
yum -y install perl-Archive-Tar 
yum -y install psmisc
yum -y install perl-DBD-MySQL 
yum -y install perl-Archive-Extract 
yum -y install net-tools 
yum -y install perl-CGI 
yum -y install perl-Switch 
yum -y install perl-File-Slurp 
yum -y install perl-DBI 
yum -y install rsync 
yum -y install telnet 
yum -y install telnet-server 
yum -y install samba 
yum -y install lshw 
yum -y install net-snmp-utils 
yum -y install gcc 
yum -y install perl-Net-DNS 
yum -y install minicom 
yum -y install lynx 
yum -y install wget 
yum -y install perl-Class-DBI-mysql 
yum -y install perl-Expect 
yum -y install telnet-server 
yum -y install perl-LDAP 
yum -y install dhcp-client 
yum -y install system-config-authentication 
yum -y install system-config-authentication-gtk 
yum -y install rpm-build 
yum -y install zlib-devel 
yum -y install autoconf 
yum -y install automake 
yum -y install openssl-devel 
yum -y install pkgconfig 
yum -y install pam-devel 
yum -y install mc 
yum -y install perl 
yum -y install samba-client 
yum -y install cups 
yum -y install make 
yum -y install net-snmp 
yum -y install bind-utils 
yum -y install bind 
yum -y install bind-libs 
yum -y install tcpdump
yum -y install xinetd
yum -y install rsyslog
yum -y install dhcp-server
yum -y install bind-libs bind-utils bind
